"""Persistence ports for the domain layer."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from .entities import AuditEvent, Course, CourseVersion, ResearchProject, Source, SourceSnapshot


class ProjectRepository(Protocol):
    async def add(self, project: ResearchProject) -> None: ...
    async def get(self, project_id: UUID) -> ResearchProject | None: ...
    async def list(self) -> list[ResearchProject]: ...
    async def update(self, project: ResearchProject) -> None: ...


class SourceRepository(Protocol):
    async def add(self, source: Source) -> None: ...
    async def get(self, source_id: UUID) -> Source | None: ...
    async def list_for_project(self, project_id: UUID) -> list[Source]: ...
    async def add_snapshot(self, snapshot: SourceSnapshot) -> None: ...
    async def list_snapshots(self, source_id: UUID) -> list[SourceSnapshot]: ...


class CourseRepository(Protocol):
    async def add(self, course: Course) -> None: ...
    async def get(self, course_id: UUID) -> Course | None: ...
    async def list_for_project(self, project_id: UUID) -> list[Course]: ...
    async def add_version(self, version: CourseVersion) -> None: ...
    async def get_version(self, version_id: UUID) -> CourseVersion | None: ...
    async def update_version(self, version: CourseVersion) -> None: ...
    async def next_version_number(self, course_id: UUID) -> int: ...


class AuditRepository(Protocol):
    async def record(self, event: AuditEvent) -> None: ...
