export const deferredChecks = [
  {
    name: "Live API integration",
    phase: "10",
    reason: "No persistent API process/data fixtures available",
    infrastructure: "FastAPI with seeded records",
    command: "NEXT_PUBLIC_MOCK_MODE=false npm run dev",
    status: "DEFERRED",
  },
  {
    name: "Production authentication",
    phase: "10",
    reason: "Identity provider/session host not selected",
    infrastructure: "Configured identity provider",
    command: "Run host authorization contract tests",
    status: "DEFERRED",
  },
  {
    name: "Live file upload",
    phase: "10",
    reason: "Object storage unavailable",
    infrastructure: "Object storage and ingestion endpoint",
    command: "Run source-file ingestion",
    status: "DEFERRED",
  },
  {
    name: "Live SSE/event streaming",
    phase: "10",
    reason: "Worker/event broker unavailable",
    infrastructure: "Worker and SSE endpoint",
    command: "Run research job event flow",
    status: "DEFERRED",
  },
  {
    name: "Mocked browser smoke",
    phase: "10",
    reason: "Package registry unavailable",
    infrastructure: "Node dependencies",
    command: "make web-e2e-mock",
    status: "DEFERRED",
  },
  {
    name: "Deployment build",
    phase: "10",
    reason: "Frontend dependencies unavailable locally",
    infrastructure: "Deployment/CI environment",
    command: "make web-build",
    status: "DEFERRED",
  },
] as const;
