from __future__ import annotations

from collections.abc import AsyncIterator, Mapping
from typing import Protocol
from uuid import UUID

from packages.domain.models import (
    AuditEvent,
    Course,
    CourseVersion,
    IngestionJob,
    ResearchProject,
    Source,
    SourceChunk,
    SourceSnapshot,
    StructuredDocument,
    Workspace,
)


class ReadinessProbe(Protocol):
    async def ping(self) -> None: ...


class WorkspaceRepository(Protocol):
    async def add(self, entity: Workspace) -> None: ...
    async def get(self, entity_id: UUID) -> Workspace | None: ...


class ResearchProjectRepository(Protocol):
    async def add(self, entity: ResearchProject) -> None: ...
    async def get(self, entity_id: UUID) -> ResearchProject | None: ...
    async def update(self, entity: ResearchProject) -> None: ...


class SourceRepository(Protocol):
    async def add(self, entity: Source) -> None: ...
    async def get(self, entity_id: UUID) -> Source | None: ...
    async def list_for_project(self, project_id: UUID) -> list[Source]: ...


class SourceSnapshotRepository(Protocol):
    async def add(self, entity: SourceSnapshot) -> None: ...
    async def list_for_source(self, source_id: UUID) -> list[SourceSnapshot]: ...


class CourseRepository(Protocol):
    async def add(self, entity: Course) -> None: ...
    async def get(self, entity_id: UUID) -> Course | None: ...


class CourseVersionRepository(Protocol):
    async def add(self, entity: CourseVersion) -> None: ...
    async def get(self, entity_id: UUID) -> CourseVersion | None: ...
    async def update_draft(self, entity: CourseVersion) -> None: ...
    async def list_for_course(self, course_id: UUID) -> list[CourseVersion]: ...


class AuditEventRepository(Protocol):
    async def append(self, entity: AuditEvent) -> None: ...


class ObjectStorage(Protocol):
    async def put_object(
        self, key: str, content: AsyncIterator[bytes], metadata: Mapping[str, str]
    ) -> None: ...
    async def get_object(self, key: str) -> AsyncIterator[bytes]: ...
    async def delete_object(self, key: str) -> None: ...
    async def object_exists(self, key: str) -> bool: ...
    async def get_object_metadata(self, key: str) -> Mapping[str, str]: ...


class DocumentParser(Protocol):
    async def parse(
        self, content: bytes, mime_type: str, filename: str | None = None
    ) -> StructuredDocument: ...


class EmbeddingProvider(Protocol):
    @property
    def model_name(self) -> str: ...
    @property
    def vector_dimension(self) -> int: ...
    async def embed_texts(self, texts: list[str]) -> list[list[float]]: ...


class ChunkRepository(Protocol):
    async def create_chunks(self, chunks: list[SourceChunk]) -> None: ...
    async def list_by_snapshot(self, snapshot_id: UUID) -> list[SourceChunk]: ...
    async def existing_hashes(self, snapshot_id: UUID) -> set[str]: ...


class IngestionJobRepository(Protocol):
    async def create(self, job: IngestionJob, request_hash: str) -> IngestionJob: ...
    async def get(self, job_id: UUID) -> IngestionJob | None: ...
    async def get_by_idempotency_key(self, key: str) -> IngestionJob | None: ...
    async def update(self, job: IngestionJob) -> None: ...
    async def get_resumable_job(self, job_id: UUID) -> IngestionJob | None: ...


class ProgressEventPublisher(Protocol):
    async def publish(self, job: IngestionJob) -> None: ...


class UnitOfWork(Protocol):
    workspaces: WorkspaceRepository
    projects: ResearchProjectRepository
    sources: SourceRepository
    snapshots: SourceSnapshotRepository
    courses: CourseRepository
    course_versions: CourseVersionRepository
    audit_events: AuditEventRepository

    async def __aenter__(self) -> UnitOfWork: ...
    async def __aexit__(self, exc_type: object, exc: object, tb: object) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
